### ISSUE TITLE
Quasar with Simple Cone

### ISSUE THREAD

**Issue by twinroot** [Kitware/trame-quasar#2]
Hello,

I managed to run the quasar example successfully but it does not have any VTK rendering components. Are there any example similar to [SimpleCone](https://kitware.github.io/trame/guide/tutorial/vtk.html) from Trame Tutorials? I couldn't figure it out  how to combine quasar with "view = vtk.VtkLocalView(renderWindow)"?

I used these code snipplets but it rendered nothing, just the toolbar with the title and a blank page.

```
with QLayout(server, view="lhh LpR lff"):
    with quasar.QHeader(
        classes="bg-black text-white",
    ):
        with quasar.QToolbar():
            quasar.QToolbarTitle("Header")

    with quasar.QPageContainer(classes="full-height"):
        #view = vtk.VtkLocalView(renderWindow) ??
        with quasar.QPage(style="padding-top: 60px", classes="q-pa-md"):
            view = vtk.VtkLocalView(renderWindow) # ??
```

Thanks.

**Comment by jourdain** [comment]
What you did is technically correct. The issue that you might run into is that the container of the VtkLocalView may not have any size (either height or width).

**Comment by jourdain** [comment]
You can use the browser dev tools to inspect the DOM and explore the various sizes of the GUI.

**Comment by twinroot** [comment]
Thanks for getting back to me. I inspected the canvas element. It comes with a height of 10:

`<canvas width="849" height="10" style="width: 100%; display: block;"></canvas>`

Despite adding all of the height hacks I know:

```
with QLayout(server, view="lhh LpR lff", style="min-height: 1000px;"):
    with quasar.QPageContainer(classes="fit bg-blue"):
        with quasar.QPage(style="width:100%; height:100%; min-height: 1000px;", classes="bg-green fit"):
            view = vtk.VtkLocalView(renderWindow)
            ctrl.view_update = view.update
            ctrl.view_reset_camera = view.reset_camera
```

Still seeing just a blank white page.
[test.txt](https://github.com/user-attachments/files/17295266/test.txt)

Attached it the example I tried. Somehow, height of the canvas is not updated.

**Comment by twinroot** [comment]
This fixed the problem:

```
with QLayout(server, view="lhh LpR lff", style="min-height: 100vh;"):
    with quasar.QPageContainer(classes="fit"):
        with quasar.QPage(classes="fit row justify-center items-center"):
            view = vtk.VtkLocalView(renderWindow, style="width: 100%; height: 100vh;")
            ctrl.view_update = view.update
            ctrl.view_reset_camera = view.reset_camera
```

**Comment by twinroot** [comment]
![Screenshot from 2024-10-08 19-11-32](https://github.com/user-attachments/assets/39a2b262-0077-413c-8810-15554c32be1e)
